# Generated by Django 4.2.9 on 2024-11-10 17:58

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description_short', models.CharField(max_length=250, verbose_name='Короткое описание')),
                ('description_long', tinymce.models.HTMLField(verbose_name='Полное описание')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото локации')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='places.place', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Фото локации',
                'verbose_name_plural': 'Фото локаций',
                'ordering': ['ordinal_number'],
            },
        ),
    ]
