# Generated by Django 4.2.9 on 2024-11-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdetailes',
            options={'verbose_name': 'Детали тура', 'verbose_name_plural': 'Детали туров'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='detailes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour', to='places.tourdetailes', verbose_name='Детали тура'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='ordinal_number',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Порядковый номер'),
        ),
    ]
