# Generated by Django 4.2 on 2024-11-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], verbose_name='Порядковый номер')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение места')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='places.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Картинка тура',
                'verbose_name_plural': 'Картинки туров',
            },
        ),
    ]
