# Generated by Django 4.2.9 on 2024-11-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_placeimage_image_place_unigue_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
