# Generated by Django 4.2.9 on 2024-11-09 20:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_tourdetailes_options_alter_tour_detailes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdetailes',
            options={'ordering': ['title'], 'verbose_name': 'Детали тура', 'verbose_name_plural': 'Детали туров'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ['ordinal_number'], 'verbose_name': 'Картинка тура', 'verbose_name_plural': 'Картинки туров'},
        ),
        migrations.AlterField(
            model_name='tourdetailes',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='ordinal_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
