# Generated by Django 4.2.9 on 2024-11-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_tourdetailes_options_alter_tourimage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourDetailes',
            new_name='TourDetails',
        ),
        migrations.RenameField(
            model_name='tourimage',
            old_name='tour_detailes',
            new_name='tour_details',
        ),
    ]
