# Generated by Django 4.2.9 on 2024-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
    ]
