# Generated by Django 4.2.9 on 2024-11-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rename_tourdetailes_tourdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='detailes',
            new_name='details',
        ),
    ]
